### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by prachi-sahani**
This PR includes login screen, logout screen and the demo of logout feature.
login and logout screen are modals and on logout the user will be redirected to the home pages

#### Login screen
ecom - login page
image

#### Signup screen
ecom - signup screen
image

#### Demo for logout screen
ecom - logout demo

### CODE REVIEW

**Review by GuptaEesh — COMMENTED** [review]
The naming looks picture perfect. Good to go.

**Review by Hamdrive — CHANGES_REQUESTED** [review]
Code looks great, website looks great as well.
Suggest to also take user firstname and lastname on signup page

**Comment by prachi-sahani** [comment]
> Code looks great, website looks great as well. Suggest to also take user firstname and lastname on signup page

Added first name and last name field
image

**Review by Hamdrive — APPROVED** [review]
Looks good, changes implemented
Can be merged!

**Pull request merged**
